module.exports = {
    apps: [{
        name: 'hospital-cms',
        script: 'src/server.js',
        instances: 'max',
        exec_mode: 'cluster',
        env: { NODE_ENV: 'development' },
        env_production: { NODE_ENV: 'production' },
        max_memory_restart: '500M',
        error_file: './logs/pm2-error.log',
        out_file: './logs/pm2-out.log',
        log_file: './logs/pm2-combined.log',
        time: true,
        watch: false,
        autorestart: true,
        restart_delay: 3000,
        max_restarts: 10,
        min_uptime: '5s',
    }],
};
